package com.example.ec.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ec.model.GreenTest;

import com.example.ec.green.GreenTestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenTestDaoConfig;

    private final GreenTestDao greenTestDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenTestDaoConfig = daoConfigMap.get(GreenTestDao.class).clone();
        greenTestDaoConfig.initIdentityScope(type);

        greenTestDao = new GreenTestDao(greenTestDaoConfig, this);

        registerDao(GreenTest.class, greenTestDao);
    }
    
    public void clear() {
        greenTestDaoConfig.clearIdentityScope();
    }

    public GreenTestDao getGreenTestDao() {
        return greenTestDao;
    }

}
